# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any

import ctypes
import struct

class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_aegis_policy_core_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_aegis_policy_core_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_aegis_policy_core_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiFfiConverterByRefBytes:
    """Zero-copy converter for `&[u8]` / `[ByRef] bytes` arguments.

    Only `lower` and `check_lower` are valid — zero-copy byte buffers only
    flow foreign -> Rust, and only in argument position. `lift`, `read`, and
    `write` have no sound implementation here.

    CPython `bytes` objects are immutable and their internal buffer doesn't
    move for the lifetime of the object; the caller must keep the source
    `bytes` alive for the duration of the FFI call.
    """

    @staticmethod
    def check_lower(value):
        # Tighter than `bytes-like`: `lower` uses `ctypes.c_char_p` which only
        # accepts `bytes`/`None`, so fail fast with a matching check.
        if not isinstance(value, bytes):
            raise TypeError("a bytes object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def lower(value):
        fb = _UniffiForeignBytes()
        if len(value) == 0:
            fb.len = 0
            fb.data = None
        else:
            fb.len = len(value)
            fb.data = ctypes.cast(ctypes.c_char_p(value), ctypes.POINTER(ctypes.c_char))
        return fb

    @staticmethod
    def lift(value):
        raise NotImplementedError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    @staticmethod
    def read(buf):
        raise NotImplementedError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    @staticmethod
    def write(value, buf):
        raise NotImplementedError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            packed = struct.pack(format, value)
            if size > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, packed, size)
    
    def write(self, value):
        length = len(value)
        with self._reserve(length):
            if length > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, value, length)

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles. 
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("aegis_policy_core")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_aegis_policy_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_aegis_policy_core_checksum_func_build_fingerprint_pipeline() != 64820:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_aegis_policy_core_checksum_func_extract_host() != 5061:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_aegis_policy_core_checksum_func_try_parse_external() != 54381:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_aegis_policy_core_checksum_method_ffibroker_create_session() != 558:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_aegis_policy_core_checksum_method_ffibroker_destroy_session() != 38937:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_aegis_policy_core_checksum_method_ffibroker_evaluate_navigation() != 5946:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_aegis_policy_core_checksum_constructor_ffibroker_new() != 18503:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_aegis_policy_core_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_aegis_policy_core_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_aegis_policy_core_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_aegis_policy_core_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_aegis_policy_core_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_aegis_policy_core_rustbuffer_free.restype = None
_UniffiLib.ffi_aegis_policy_core_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_aegis_policy_core_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_aegis_policy_core_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_aegis_policy_core_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_aegis_policy_core_checksum_func_build_fingerprint_pipeline.argtypes = (
)
_UniffiLib.uniffi_aegis_policy_core_checksum_func_build_fingerprint_pipeline.restype = ctypes.c_uint16
_UniffiLib.uniffi_aegis_policy_core_checksum_func_extract_host.argtypes = (
)
_UniffiLib.uniffi_aegis_policy_core_checksum_func_extract_host.restype = ctypes.c_uint16
_UniffiLib.uniffi_aegis_policy_core_checksum_func_try_parse_external.argtypes = (
)
_UniffiLib.uniffi_aegis_policy_core_checksum_func_try_parse_external.restype = ctypes.c_uint16
_UniffiLib.uniffi_aegis_policy_core_checksum_method_ffibroker_create_session.argtypes = (
)
_UniffiLib.uniffi_aegis_policy_core_checksum_method_ffibroker_create_session.restype = ctypes.c_uint16
_UniffiLib.uniffi_aegis_policy_core_checksum_method_ffibroker_destroy_session.argtypes = (
)
_UniffiLib.uniffi_aegis_policy_core_checksum_method_ffibroker_destroy_session.restype = ctypes.c_uint16
_UniffiLib.uniffi_aegis_policy_core_checksum_method_ffibroker_evaluate_navigation.argtypes = (
)
_UniffiLib.uniffi_aegis_policy_core_checksum_method_ffibroker_evaluate_navigation.restype = ctypes.c_uint16
_UniffiLib.uniffi_aegis_policy_core_checksum_constructor_ffibroker_new.argtypes = (
)
_UniffiLib.uniffi_aegis_policy_core_checksum_constructor_ffibroker_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_aegis_policy_core_fn_func_build_fingerprint_pipeline.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_aegis_policy_core_fn_func_build_fingerprint_pipeline.restype = _UniffiRustBuffer
_UniffiLib.uniffi_aegis_policy_core_fn_func_extract_host.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_aegis_policy_core_fn_func_extract_host.restype = _UniffiRustBuffer
_UniffiLib.uniffi_aegis_policy_core_fn_func_try_parse_external.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_aegis_policy_core_fn_func_try_parse_external.restype = _UniffiRustBuffer
_UniffiLib.uniffi_aegis_policy_core_fn_method_ffibroker_create_session.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_aegis_policy_core_fn_method_ffibroker_create_session.restype = ctypes.c_int8
_UniffiLib.uniffi_aegis_policy_core_fn_method_ffibroker_destroy_session.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_aegis_policy_core_fn_method_ffibroker_destroy_session.restype = ctypes.c_int8
_UniffiLib.uniffi_aegis_policy_core_fn_method_ffibroker_evaluate_navigation.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_aegis_policy_core_fn_method_ffibroker_evaluate_navigation.restype = _UniffiRustBuffer
_UniffiLib.uniffi_aegis_policy_core_fn_constructor_ffibroker_new.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_aegis_policy_core_fn_constructor_ffibroker_new.restype = ctypes.c_uint64
_UniffiLib.uniffi_aegis_policy_core_fn_clone_ffibroker.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_aegis_policy_core_fn_clone_ffibroker.restype = ctypes.c_uint64
_UniffiLib.uniffi_aegis_policy_core_fn_free_ffibroker.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_aegis_policy_core_fn_free_ffibroker.restype = None

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

class _UniffiFfiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

@dataclass
class FfiAuthorizedAction:
    """
    FFI 版授权行动（与 decision::AuthorizedAction 字段一致）。
"""
    def __init__(self, *, session_id:str, tab_id:str, document_generation:int, origin:str, method:str, canonical_parameters:str, scope:str, expires_at:int, nonce:str, policy_version:str, explanation:str):
        self.session_id = session_id
        self.tab_id = tab_id
        self.document_generation = document_generation
        self.origin = origin
        self.method = method
        self.canonical_parameters = canonical_parameters
        self.scope = scope
        self.expires_at = expires_at
        self.nonce = nonce
        self.policy_version = policy_version
        self.explanation = explanation
        
        

    
    def __str__(self):
        return "FfiAuthorizedAction(session_id={}, tab_id={}, document_generation={}, origin={}, method={}, canonical_parameters={}, scope={}, expires_at={}, nonce={}, policy_version={}, explanation={})".format(self.session_id, self.tab_id, self.document_generation, self.origin, self.method, self.canonical_parameters, self.scope, self.expires_at, self.nonce, self.policy_version, self.explanation)
    def __eq__(self, other):
        if self.session_id != other.session_id:
            return False
        if self.tab_id != other.tab_id:
            return False
        if self.document_generation != other.document_generation:
            return False
        if self.origin != other.origin:
            return False
        if self.method != other.method:
            return False
        if self.canonical_parameters != other.canonical_parameters:
            return False
        if self.scope != other.scope:
            return False
        if self.expires_at != other.expires_at:
            return False
        if self.nonce != other.nonce:
            return False
        if self.policy_version != other.policy_version:
            return False
        if self.explanation != other.explanation:
            return False
        return True

class _UniffiFfiConverterTypeFfiAuthorizedAction(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiAuthorizedAction(
            session_id=_UniffiFfiConverterString.read(buf),
            tab_id=_UniffiFfiConverterString.read(buf),
            document_generation=_UniffiFfiConverterUInt64.read(buf),
            origin=_UniffiFfiConverterString.read(buf),
            method=_UniffiFfiConverterString.read(buf),
            canonical_parameters=_UniffiFfiConverterString.read(buf),
            scope=_UniffiFfiConverterString.read(buf),
            expires_at=_UniffiFfiConverterUInt64.read(buf),
            nonce=_UniffiFfiConverterString.read(buf),
            policy_version=_UniffiFfiConverterString.read(buf),
            explanation=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.session_id)
        _UniffiFfiConverterString.check_lower(value.tab_id)
        _UniffiFfiConverterUInt64.check_lower(value.document_generation)
        _UniffiFfiConverterString.check_lower(value.origin)
        _UniffiFfiConverterString.check_lower(value.method)
        _UniffiFfiConverterString.check_lower(value.canonical_parameters)
        _UniffiFfiConverterString.check_lower(value.scope)
        _UniffiFfiConverterUInt64.check_lower(value.expires_at)
        _UniffiFfiConverterString.check_lower(value.nonce)
        _UniffiFfiConverterString.check_lower(value.policy_version)
        _UniffiFfiConverterString.check_lower(value.explanation)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.session_id, buf)
        _UniffiFfiConverterString.write(value.tab_id, buf)
        _UniffiFfiConverterUInt64.write(value.document_generation, buf)
        _UniffiFfiConverterString.write(value.origin, buf)
        _UniffiFfiConverterString.write(value.method, buf)
        _UniffiFfiConverterString.write(value.canonical_parameters, buf)
        _UniffiFfiConverterString.write(value.scope, buf)
        _UniffiFfiConverterUInt64.write(value.expires_at, buf)
        _UniffiFfiConverterString.write(value.nonce, buf)
        _UniffiFfiConverterString.write(value.policy_version, buf)
        _UniffiFfiConverterString.write(value.explanation, buf)

@dataclass
class FfiDenyReason:
    """
    FFI 版拒绝原因。
"""
    def __init__(self, *, code:str, detail:str, explanation:str):
        self.code = code
        self.detail = detail
        self.explanation = explanation
        
        

    
    def __str__(self):
        return "FfiDenyReason(code={}, detail={}, explanation={})".format(self.code, self.detail, self.explanation)
    def __eq__(self, other):
        if self.code != other.code:
            return False
        if self.detail != other.detail:
            return False
        if self.explanation != other.explanation:
            return False
        return True

class _UniffiFfiConverterTypeFfiDenyReason(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiDenyReason(
            code=_UniffiFfiConverterString.read(buf),
            detail=_UniffiFfiConverterString.read(buf),
            explanation=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.code)
        _UniffiFfiConverterString.check_lower(value.detail)
        _UniffiFfiConverterString.check_lower(value.explanation)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.code, buf)
        _UniffiFfiConverterString.write(value.detail, buf)
        _UniffiFfiConverterString.write(value.explanation, buf)

@dataclass
class FfiOrigin:
    """
    FFI 版 URL 解析结果（UniFFI 不支持元组返回——用 Record）。
"""
    def __init__(self, *, scheme:str, host:str):
        self.scheme = scheme
        self.host = host
        
        

    
    def __str__(self):
        return "FfiOrigin(scheme={}, host={})".format(self.scheme, self.host)
    def __eq__(self, other):
        if self.scheme != other.scheme:
            return False
        if self.host != other.host:
            return False
        return True

class _UniffiFfiConverterTypeFfiOrigin(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiOrigin(
            scheme=_UniffiFfiConverterString.read(buf),
            host=_UniffiFfiConverterString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.scheme)
        _UniffiFfiConverterString.check_lower(value.host)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.scheme, buf)
        _UniffiFfiConverterString.write(value.host, buf)






class FfiDecision:
    """
    FFI 版安全决策（枚举——Allow/Deny/RequireConfirmation）。
"""
    def __init__(self):
        raise RuntimeError("FfiDecision cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    @dataclass
    class ALLOW:
        
        def __init__(self, action:FfiAuthorizedAction):
            self.action = action
            
            
            pass

    
            
            
    
        def __str__(self):
            return "FfiDecision.ALLOW(action={})".format(self.action)
        def __eq__(self, other):
            if not isinstance(other, FfiDecision):
                return NotImplemented
            if not other.is_ALLOW():
                return False
            if self.action != other.action:
                return False
            return True

    @dataclass
    class REQUIRE_CONFIRMATION:
        
        def __init__(self, origin:str, method:str):
            self.origin = origin
            
            
            self.method = method
            
            
            pass

    
            
            
    
        def __str__(self):
            return "FfiDecision.REQUIRE_CONFIRMATION(origin={}, method={})".format(self.origin, self.method)
        def __eq__(self, other):
            if not isinstance(other, FfiDecision):
                return NotImplemented
            if not other.is_REQUIRE_CONFIRMATION():
                return False
            if self.origin != other.origin:
                return False
            if self.method != other.method:
                return False
            return True

    @dataclass
    class DENY:
        
        def __init__(self, reason:FfiDenyReason):
            self.reason = reason
            
            
            pass

    
            
            
    
        def __str__(self):
            return "FfiDecision.DENY(reason={})".format(self.reason)
        def __eq__(self, other):
            if not isinstance(other, FfiDecision):
                return NotImplemented
            if not other.is_DENY():
                return False
            if self.reason != other.reason:
                return False
            return True

    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_ALLOW(self) -> bool:
        return isinstance(self, FfiDecision.ALLOW)
    def is_allow(self) -> bool:
        return isinstance(self, FfiDecision.ALLOW)
    def is_REQUIRE_CONFIRMATION(self) -> bool:
        return isinstance(self, FfiDecision.REQUIRE_CONFIRMATION)
    def is_require_confirmation(self) -> bool:
        return isinstance(self, FfiDecision.REQUIRE_CONFIRMATION)
    def is_DENY(self) -> bool:
        return isinstance(self, FfiDecision.DENY)
    def is_deny(self) -> bool:
        return isinstance(self, FfiDecision.DENY)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
FfiDecision.ALLOW = type("FfiDecision.ALLOW", (FfiDecision.ALLOW, FfiDecision,), {})  # type: ignore
FfiDecision.REQUIRE_CONFIRMATION = type("FfiDecision.REQUIRE_CONFIRMATION", (FfiDecision.REQUIRE_CONFIRMATION, FfiDecision,), {})  # type: ignore
FfiDecision.DENY = type("FfiDecision.DENY", (FfiDecision.DENY, FfiDecision,), {})  # type: ignore




class _UniffiFfiConverterTypeFfiDecision(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiDecision.ALLOW(
                _UniffiFfiConverterTypeFfiAuthorizedAction.read(buf),
            )
        if variant == 2:
            return FfiDecision.REQUIRE_CONFIRMATION(
                _UniffiFfiConverterString.read(buf),
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return FfiDecision.DENY(
                _UniffiFfiConverterTypeFfiDenyReason.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_ALLOW():
            _UniffiFfiConverterTypeFfiAuthorizedAction.check_lower(value.action)
            return
        if value.is_REQUIRE_CONFIRMATION():
            _UniffiFfiConverterString.check_lower(value.origin)
            _UniffiFfiConverterString.check_lower(value.method)
            return
        if value.is_DENY():
            _UniffiFfiConverterTypeFfiDenyReason.check_lower(value.reason)
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_ALLOW():
            buf.write_i32(1)
            _UniffiFfiConverterTypeFfiAuthorizedAction.write(value.action, buf)
        if value.is_REQUIRE_CONFIRMATION():
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value.origin, buf)
            _UniffiFfiConverterString.write(value.method, buf)
        if value.is_DENY():
            buf.write_i32(3)
            _UniffiFfiConverterTypeFfiDenyReason.write(value.reason, buf)



class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)


class FfiBrokerProtocol(typing.Protocol):
    """
    FFI 版 Broker——跨语言导航决策（委托 ContextBroker）。

    C#/Kotlin/Python 各自实例化，替代三语言重复的 Broker 实现。
    内部用 Mutex 提供可变性——UniFFI Object 方法只支持 &self（Arc 只读）。
"""
    
    def create_session(self, session_id: str,tab_id: str,generation: int,ttl_seconds: int) -> bool:
        """
        创建新会话（ttl 秒）。
"""
        raise NotImplementedError
    def destroy_session(self, session_id: str) -> bool:
        """
        销毁会话。
"""
        raise NotImplementedError
    def evaluate_navigation(self, session_id: str,tab_id: str,generation: int,raw_url: str,scope: str) -> FfiDecision:
        """
        评估导航意图（URL 解析 + 会话验证 → FfiDecision——fail-closed）。
"""
        raise NotImplementedError

class FfiBroker(FfiBrokerProtocol):
    """
    FFI 版 Broker——跨语言导航决策（委托 ContextBroker）。

    C#/Kotlin/Python 各自实例化，替代三语言重复的 Broker 实现。
    内部用 Mutex 提供可变性——UniFFI Object 方法只支持 &self（Arc 只读）。
"""
    
    _handle: ctypes.c_uint64
    def __init__(self, policy_version: str):
        """
        创建 Broker（policy_version 锁定——INV-03 一致性）。
"""
        
        _UniffiFfiConverterString.check_lower(policy_version)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(policy_version),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFfiBroker.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_aegis_policy_core_fn_constructor_ffibroker_new,
            *_uniffi_lowered_args,
        )
        self._handle = _uniffi_ffi_result

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_aegis_policy_core_fn_free_ffibroker, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_aegis_policy_core_fn_clone_ffibroker, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def create_session(self, session_id: str,tab_id: str,generation: int,ttl_seconds: int) -> bool:
        """
        创建新会话（ttl 秒）。
"""
        
        _UniffiFfiConverterString.check_lower(session_id)

        _UniffiFfiConverterString.check_lower(tab_id)

        _UniffiFfiConverterUInt64.check_lower(generation)

        _UniffiFfiConverterUInt64.check_lower(ttl_seconds)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(session_id),
            _UniffiFfiConverterString.lower(tab_id),
            _UniffiFfiConverterUInt64.lower(generation),
            _UniffiFfiConverterUInt64.lower(ttl_seconds),
        )
        _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_aegis_policy_core_fn_method_ffibroker_create_session,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def destroy_session(self, session_id: str) -> bool:
        """
        销毁会话。
"""
        
        _UniffiFfiConverterString.check_lower(session_id)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(session_id),
        )
        _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_aegis_policy_core_fn_method_ffibroker_destroy_session,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def evaluate_navigation(self, session_id: str,tab_id: str,generation: int,raw_url: str,scope: str) -> FfiDecision:
        """
        评估导航意图（URL 解析 + 会话验证 → FfiDecision——fail-closed）。
"""
        
        _UniffiFfiConverterString.check_lower(session_id)

        _UniffiFfiConverterString.check_lower(tab_id)

        _UniffiFfiConverterUInt64.check_lower(generation)

        _UniffiFfiConverterString.check_lower(raw_url)

        _UniffiFfiConverterString.check_lower(scope)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(session_id),
            _UniffiFfiConverterString.lower(tab_id),
            _UniffiFfiConverterUInt64.lower(generation),
            _UniffiFfiConverterString.lower(raw_url),
            _UniffiFfiConverterString.lower(scope),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFfiDecision.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_aegis_policy_core_fn_method_ffibroker_evaluate_navigation,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeFfiBroker:
    @staticmethod
    def lift(value: int) -> FfiBroker:
        return FfiBroker._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: FfiBroker):
        if not isinstance(value, FfiBroker):
            raise TypeError("Expected FfiBroker instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: FfiBroker) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> FfiBroker:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: FfiBroker, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

class _UniffiFfiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterOptionalTypeFfiOrigin(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeFfiOrigin.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeFfiOrigin.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeFfiOrigin.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")
def build_fingerprint_pipeline(session_seed: str) -> str:
    """
    生成指纹防护管道 JS（委托 fingerprint_pipeline 逻辑——跨端统一）。
"""
    
    _UniffiFfiConverterString.check_lower(session_seed)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(session_seed),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_aegis_policy_core_fn_func_build_fingerprint_pipeline,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def extract_host(url: str) -> typing.Optional[str]:
    """
    URL 主机名提取（委托 util 模块）。
"""
    
    _UniffiFfiConverterString.check_lower(url)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(url),
    )
    _uniffi_lift_return = _UniffiFfiConverterOptionalString.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_aegis_policy_core_fn_func_extract_host,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def try_parse_external(raw_url: str) -> typing.Optional[FfiOrigin]:
    """
    URL 校验（委托 origin 模块——消除 C#/Kotlin/Python 重复实现）。

    返回 `FfiOrigin { scheme, host }` 或 None（URL 非法）。
"""
    
    _UniffiFfiConverterString.check_lower(raw_url)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(raw_url),
    )
    _uniffi_lift_return = _UniffiFfiConverterOptionalTypeFfiOrigin.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_aegis_policy_core_fn_func_try_parse_external,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)

__all__ = [
    "InternalError",
    "FfiDecision",
    "FfiAuthorizedAction",
    "FfiDenyReason",
    "FfiOrigin",
    "build_fingerprint_pipeline",
    "extract_host",
    "try_parse_external",
    "FfiBroker",
    "FfiBrokerProtocol",
]