PRODUCT=Aegis
DISPLAY_NAME=Aegis WebView
VERSION_NAME=2.1.9
VERSION_CODE=20109
WINDOWS_PACKAGE_VERSION=2.1.9.0
WINDOWS_PACKAGE_IDENTITY=Aegis.Project.AegisWebView
ANDROID_APPLICATION_ID=com.aegis.browser
