PRODUCT=Aegis
DISPLAY_NAME=Aegis WebView
VERSION_NAME=2.2.0-beta.6
VERSION_CODE=20205
WINDOWS_PACKAGE_VERSION=2.2.0.6
WINDOWS_PACKAGE_IDENTITY=Aegis.Project.AegisWebView
ANDROID_APPLICATION_ID=com.aegis.browser
