PRODUCT=Aegis
DISPLAY_NAME=Aegis WebView
VERSION_NAME=2.2.0-beta.43
VERSION_CODE=20242
WINDOWS_PACKAGE_VERSION=2.2.0.43
WINDOWS_PACKAGE_IDENTITY=Aegis.Project.AegisWebView
ANDROID_APPLICATION_ID=com.aegis.browser
